//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.07 at 05:24:21 PM ICT 
//


package com.sonic.aoeleague.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sonic.aoeleague.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sonic.aoeleague.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AoeLeague }
     * 
     */
    public AoeLeague createAoeLeague() {
        return new AoeLeague();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link UpdateLogData }
     * 
     */
    public UpdateLogData createUpdateLogData() {
        return new UpdateLogData();
    }

    /**
     * Create an instance of {@link UpdateLog }
     * 
     */
    public UpdateLog createUpdateLog() {
        return new UpdateLog();
    }

    /**
     * Create an instance of {@link GraphData }
     * 
     */
    public GraphData createGraphData() {
        return new GraphData();
    }

    /**
     * Create an instance of {@link NewbieGraph }
     * 
     */
    public NewbieGraph createNewbieGraph() {
        return new NewbieGraph();
    }

    /**
     * Create an instance of {@link NickName }
     * 
     */
    public NickName createNickName() {
        return new NickName();
    }

    /**
     * Create an instance of {@link AoeRequest }
     * 
     */
    public AoeRequest createAoeRequest() {
        return new AoeRequest();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link PlayerInfo }
     * 
     */
    public PlayerInfo createPlayerInfo() {
        return new PlayerInfo();
    }

    /**
     * Create an instance of {@link PlayerAnalysis }
     * 
     */
    public PlayerAnalysis createPlayerAnalysis() {
        return new PlayerAnalysis();
    }

    /**
     * Create an instance of {@link AoeResponse }
     * 
     */
    public AoeResponse createAoeResponse() {
        return new AoeResponse();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link NewbieGraphElement }
     * 
     */
    public NewbieGraphElement createNewbieGraphElement() {
        return new NewbieGraphElement();
    }

    /**
     * Create an instance of {@link UpdatePlayer }
     * 
     */
    public UpdatePlayer createUpdatePlayer() {
        return new UpdatePlayer();
    }

    /**
     * Create an instance of {@link UpdatePlayerInfo }
     * 
     */
    public UpdatePlayerInfo createUpdatePlayerInfo() {
        return new UpdatePlayerInfo();
    }

}
